### ISSUE TITLE
AttributeError: 'int' object has no attribute 'strip'

### ISSUE THREAD

**Issue by BaltashovIlia** [ros-visualization/rqt_tf_tree#27]
Hi, 

rqt_tf_tree does not work if tf contains a frame with a name consisting only of numbers. For example:  
rosrun tf2_ros static_transform_publisher 0 0 0 0 0 0 1 map 239 

My system is: Ubuntu 20.04, Python 3.8.5, ROS  noetic, rqt_tf_tree 0.6.2. 

Error message is:
```
PluginHandlerDirect._restore_settings() plugin "rqt_tf_tree/RosTfTree#1" raised an exception:
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler_direct.py", line 121, in _restore_settings
    self._plugin.restore_settings(plugin_settings_plugin, instance_settings_plugin)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_tf_tree/tf_tree.py", line 131, in restore_settings
    self._refresh_tf_graph()
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_tf_tree/tf_tree.py", line 143, in _refresh_tf_graph
    self._update_graph_view(self._generate_dotcode())
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_tf_tree/tf_tree.py", line 150, in _generate_dotcode
    return self.dotcode_generator.generate_dotcode(dotcode_factory=self.dotcode_factory,
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_tf_tree/dotcode_tf.py", line 97, in generate_dotcode
    self.graph = self.generate(data, timer.now().to_sec())
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_tf_tree/dotcode_tf.py", line 118, in generate
    self.dotcode_factory.add_node_to_graph(
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_dotgraph/pydotfactory.py", line 102, in add_node_to_graph
    node = pydot.Node(self.escape_name(nodename))
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_dotgraph/pydotfactory.py", line 58, in escape_name
    ret = quote(name.strip())
AttributeError: 'int' object has no attribute 'strip' 
```

**Comment by ahcorde** [comment]
PR https://github.com/ros-visualization/rqt_tf_tree/pull/52
