### ISSUE TITLE
python update to 3,rosrun rqt_tf_tree failed

### ISSUE THREAD

**Issue by Wuxinxiaoshifu** [ros-visualization/rqt_tf_tree#34]
rosrun rqt_tf_tree rqt_tf_tree 
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/rqt_tf_tree/rqt_tf_tree", line 8, in <module>
    sys.exit(main.main(sys.argv, standalone='rqt_tf_tree.tf_tree.RosTfTree'))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_gui/main.py", line 65, in main
    hash(os.environ['ROS_PACKAGE_PATH'])))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/main.py", line 407, in main
    from python_qt_binding import QT_BINDING
  File "/opt/ros/melodic/lib/python2.7/dist-packages/python_qt_binding/__init__.py", line 55, in <module>
    from .binding_helper import loadUi, QT_BINDING, QT_BINDING_MODULES, QT_BINDING_VERSION  # @UnusedImport
  File "/opt/ros/melodic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 276, in <module>
    getattr(sys, 'SELECT_QT_BINDING_ORDER', None),
  File "/opt/ros/melodic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 108, in _select_qt_binding
    QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 155, in _load_pyqt
    _named_optional_import('PyQt5.%s' % module_name)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 142, in _named_optional_import
    _named_import(name)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 133, in _named_import
    module = builtins.__import__(name)
ValueError: PyCapsule_GetPointer called with incorrect name

**Comment by mabelzhang** [comment]
Looks like your printouts are from python2.7, even though you said you updated to Python 3. There's some inconsistencies there.
It also looks like you're running Melodic, which the official support is with Python 2 on Ubuntu 18.04.
